### PR TITLE
Fix RGB <--> CMY color conversions

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR
  * adds functionally to automatically adjust color schema in the `.tex` preamble if there are CMY colors within the logo colors (`ORIG_COLORS ` variable)
  * removes old stuff from directory

### CODE REVIEW

**Review by knaaptime — APPROVED** [review]
looks like this helps the blending a bit? looks nice

also sorry for accidentally pushing straight to the new branch last night and eschewing the model I *just* advocated 😑

**Comment by jGaboardi** [comment]
> looks like this helps the blending a bit? looks nice

This should completely fix the blending issue. I tested it with magenta and yellow locally (see below for example). All appears in order.

pysal_logo

**Comment by knaaptime** [comment]
nice! this is great! though i still struggle with the brightness of that magenta

**Comment by jGaboardi** [comment]
> nice! this is great! though i still struggle with the brightness of that magenta

In the [original PySAL design](https://github.com/pysal) there is no magenta (that's what I based the colors from in the [`ORIG_COLORS` variable](https://github.com/pysal/logo/pull/6/files#diff-c6c3c0fc97049909c38dff79d4ddc9fcR64-R72). However, if a magenta-ish color was desired that was toned-down it could be done with something like [`black!25!magenta` or (the like)](https://github.com/pysal/logo/pull/6/files#diff-c6c3c0fc97049909c38dff79d4ddc9fcR68).

**Comment by jGaboardi** [comment]
I am personally not a fan of the magenta (I prefer the standard red and/or wine). However, any(?) blend is possible. Here are other examples. 


```python
alphas = numpy.linspace(0,100,7)
colors = ["black!%s!magenta" % alpha for alpha in alphas]
```
pysal_logo

-------------------------

```python
alphas = numpy.linspace(0,100,7)
colors = ["white!%s!magenta" % alpha for alpha in alphas]
```
pysal_logo

---------------------



```python
alphas = numpy.linspace(0,100,7)
colors = ["cyan!%s!magenta" % alpha for alpha in alphas]
```
pysal_logo

**Comment by knaaptime** [comment]
I like this one 
image

and this one 

image

**Comment by jGaboardi** [comment]
[gist](https://gist.github.com/jGaboardi/3456d903ed5da671fd5c8b2d13767f1d) of the logo examples notebook from 1981a11

**Comment by jGaboardi** [comment]
This PR also addresses the repo reorg issue (#7).

**Pull request merged**
